### PR TITLE
Have resolved inputNode crash issue in audioEngine

### PR DESCRIPTION
**Pull request by karthironald**
1. Have resolved audio engine inputNode optional issue. 
2. Have removed bus on stopping recording to avoid crash.

### CODE REVIEW

**Comment by simonbromberg** [comment]
Thank you for your contribution to this project, I have neglected it for a while, but I will give your changes a whirl soon.

**Comment by simonbromberg** [comment]
Could you give me more information on what "crash issue" you're trying to solve here?

Your branch seems to have compilation errors because the optional `input` node is not unwrapped because you removed the `guard let`…

**Comment by karthironald** [comment]
1. When I was running it in `Swift 4.1` and `Xcode 9.3`, I got error like inputNode is not an optional to use `guard let`. So I have remove it. 
2. When I stop recording and start again, I got an crash like input bus is not removed on tap. So I have added bus removing logic on tap.

**Comment by simonbromberg** [comment]
What version of iOS are you using?

**Comment by karthironald** [comment]
iOS 11.3 (15E5167f), iPhone 7

**Comment by simonbromberg** [comment]
Ah looks Apple changed it in iOS 11 to not be optional.

**Comment by simonbromberg** [comment]
While generally one wants to make a library like this backwards compatible, I suppose in this case it's not really a concern.

**Comment by simonbromberg** [comment]
Thanks for your contribution

**Comment by simonbromberg** [comment]
I have also updated the project / example project to use iOS 11.3 and Swift 4, plus removed the Pods folder synced in the example project folder.

**Comment by karthironald** [comment]
Thanks..😀

**Pull request merged**
